### ISSUE TITLE
Enhance price predictions?

### ISSUE THREAD

**Issue by slave2sync** [gs1803/Stock-Market-Analyzer-ST#1]
Thank you for this wonderful work! I was wondering if one could enhance the predictions to define two different time windows: one from which the training can be based on and another time window for the prediction. In this way you could potentially see a prediction further ahead in time but also to evaluate the potential of the model to capture market reversals. This was just a thought :) Thanks again for this work!
Warm regards

**Comment by gs1803** [comment]
Hi, thank you for your comment!! That sounds like a good idea, and I’ll see what I can do to implement it. In terms of long term forecasting, I am planning to implement ARMA, ARIMA, FB Prophet and other forecasting techniques since they tend to provide better results.
Regards
